services:
  app:
    build: .
    container_name: hotel-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/hotel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
    ports:
      - "8080:8080"

    depends_on:
      - activemq

  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq-classic
    ports:
      - "61616:61616"
      - "8161:8161"
